# Generated by Django 4.2.29 on 2026-03-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_alter_teacher_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='examplemodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train', models.CharField(max_length=25)),
            ],
        ),
    ]
