# Generated by Django 4.2.29 on 2026-05-18 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_alter_teacher_id_alter_unit_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('audio', models.FileField(upload_to='audio/', validators=[django.core.validators.FileExtensionValidator(['mp3'])])),
            ],
        ),
    ]
