# Generated by Django 4.2.29 on 2026-05-18 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_audiofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='mp3_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/', validators=[django.core.validators.FileExtensionValidator(['mp3'])]),
        ),
    ]
