# Generated by Django 4.2.29 on 2026-05-18 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_teacher_mp3_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='mp3_file',
        ),
    ]
